export default {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',

  POST_PRODUCT: 'POST_PRODUCT',
  POST_PRODUCT_SUCCESS: 'POST_PRODUCT_SUCCESS',
  POST_PRODUCT_ERROR: 'POST_PRODUCT_ERROR',

  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',

  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',

  GET_PRODUCT_BY_ID: 'GET_PRODUCT_BY_ID',
  GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',
  GET_PRODUCT_BY_ID_ERROR: 'GET_PRODUCT_BY_ID_ERROR',

  DEL_PRODUCT: 'DEL_PRODUCT',
}