import photo from './assets/images/img.jpg'
export const listProducts = [
  {
    id: Math.random(),
    photo,
    name: 'product1',
    describe: 'describe the product',
    price: 100,
  },
  {
    id: Math.random(),
    photo,
    name: 'product2',
    describe: 'describe',
    price: 500,
  },
  {
    id: Math.random(),
    photo,
    name: 'product3',
    describe: 'describe the product',
    price: 1005,
  },
  {
    id: Math.random(),
    photo,
    name: 'product4',
    describe: 'describe the product',
    price: 1,
  },
  {
    id: Math.random(),
    photo,
    name: 'product234',
    describe: 'describe the product',
    price: 555,
  },
  {
    id: Math.random(),
    photo,
    name: 'product45',
    describe: 'describe the product',
    price: 222,
  },
  {
    id: Math.random(),
    photo,
    name: 'product4',
    describe: 'describe the product',
    price: 1,
  },
  {
    id: Math.random(),
    photo,
    name: 'product234',
    describe: 'describe the product',
    price: 555,
  },
  {
    id: Math.random(),
    photo,
    name: 'product45',
    describe: 'describe the product',
    price: 222,
  },
  {
    id: Math.random(),
    photo,
    name: 'product4',
    describe: 'describe the product',
    price: 1,
  },
  {
    id: Math.random(),
    photo,
    name: 'product234',
    describe: 'describe the product',
    price: 555,
  },
  {
    id: Math.random(),
    photo,
    name: 'product45',
    describe: 'describe the product',
    price: 222,
  },
  {
    id: Math.random(),
    photo,
    name: 'product4',
    describe: 'describe the product',
    price: 1,
  },
  {
    id: Math.random(),
    photo,
    name: 'product234',
    describe: 'describe the product',
    price: 555,
  },
  {
    id: Math.random(),
    photo,
    name: 'product45',
    describe: 'describe the product',
    price: 222,
  },
]
